repos:
  # --- General hygiene hooks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # --- Code formatting ---
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile=black"]

  # --- Linting ---
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  # --- Run tests before commit ---
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'PYTHONPATH=. pytest -q'
        language: system
        pass_filenames: false
        always_run: true
