# configs/training.yaml
target: churn

data:
  path: data/raw/customer_churn.json  # data JSONL file

features:
  drop: ["firstName", "lastName"]
  inactivity_days: 30   # users inactive >= N days are churned (unless explicit)

imbalance:
  method: class_weight

metrics: ["roc_auc", "average_precision", "f1", "accuracy", "precision", "recall", "lift"]
primary_metric: roc_auc

logging:
  level: DEBUG
